name: Standard_Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  lint:
    permissions:
      checks: write  # for coverallsapp/github-action to create new checks
      contents: read  # for actions/checkout to fetch code
    name: Lint
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [16]
    runs-on: ${{ matrix.os }}
    env:
      TEST_ENV: ${{ matrix.test_env || 'production' }}

    services:
      mongo:
        image: 'mongo:3.7'
        ports:
          # Maps port 27017 on service container to the host
          - 27017:27017

    steps:
      - uses: actions/checkout@v3

      - run: cp install/package.json package.json

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: NPM Install
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Setup on MongoDB
        env:
          SETUP: >-
            {
              "url": "http://127.0.0.1:4567",
              "secret": "abcdef",
              "admin:username": "admin",
              "admin:email": "test@example.org",
              "admin:password": "hAN3Eg8W",
              "admin:password:confirm": "hAN3Eg8W",

              "database": "mongo",
              "mongo:host": "127.0.0.1",
              "mongo:port": 27017,
              "mongo:username": "",
              "mongo:password": "",
              "mongo:database": "nodebb"
            }
          CI: >-
            {
              "host": "127.0.0.1",
              "port": 27017,
              "database": "ci_test"
            }
        run: |
          node app --setup="${SETUP}" --ci="${CI}"

      - name: Get Base Branch Commit SHA
        id: base_branch_commit
        run: echo "::set-output name=sha::$(git rev-parse ${{ github.event.repository.default_branch }})"

      - name: Display Base Branch Commit SHA
        id: base_branch_sha
        run: echo "Base Branch Commit SHA ${{ steps.base_branch_commit.outputs.sha }}"

      - name: Get Head Branch Commit SHA
        id: head_branch_commit
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Display Head Branch Commit SHA
        id: head_branch_sha
        run: echo "Head Branch Commit SHA ${{ steps.head_branch_commit.outputs.sha }}"
      
      - name: Get list of Changed Files
        id: getfile
        run: |
          files=$(git diff --name-only ${{ steps.base_branch_sha }} ${{ steps.head_branch_sha }})
          echo "::set-output name=files::$files"
      
      - name: Run Tool on Changed Files
        run: |
          FILES="${{ steps.getfile.outputs.files }}"
          
          for file in $FILES; do
            npx standard $file
            echo "Changed file: $file"
          done
